### ISSUE TITLE
Warning in 7.0.1-alpine

### ISSUE THREAD

**Issue by panki3a** [mvhirsch/thumbor-docker#11]
Hi,
I am testing your 7.0.1-alpine image.
I get this warning in log

thumbor:WARNING pycurl usage is advised. It could not be loaded properly. Verify install...

**Comment by mvhirsch** [comment]
Thank you for testing!

> thumbor:WARNING pycurl usage is advised. It could not be loaded properly. Verify install...

This is actually expected on alpine, since I do not install `pycurl`. I actually left this package, cause of reducing image size. Thumbor works pretty fine without, but if you want to use it, you can actually install it. 

If you need help on how to do this, just leave me another message.

Greets

**Comment by panki3a** [comment]
Yes, thumbor works fine, in logs, there arent any others warning.
I dont know, if i need this library :) 
I can live with one warning in console ;)
